// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Congratulate: typeof import('./src/pages/init/Finish.vue')['default']
    CreateProfile: typeof import('./src/pages/init/CreateProfile.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Finish: typeof import('./src/pages/init/Finish.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/pages/main/Home.vue')['default']
    Index: typeof import('./src/pages/init/Index.vue')['default']
    IndexPage: typeof import('./src/pages/IndexPage.vue')['default']
    Intro: typeof import('./src/pages/init/Intro.vue')['default']
    Popup: typeof import('./src/pages/Popup.vue')['default']
    Profile: typeof import('./src/components/pages/Profile.vue')['default']
    Profiles: typeof import('./src/components/Profiles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
